=== chamuch/vtlcagw/cagw-core/src/main/resources/META-INF/cagw-core/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (section+)>
<!ELEMENT section (property+, router*)>
<!ELEMENT property EMPTY>
<!ELEMENT router (ranges, values)>
<!ELEMENT ranges (range+)>
<!ELEMENT values (value+)>
<!ELEMENT range EMPTY>
<!ELEMENT value EMPTY>

<!ATTLIST section
	id 			ID 		#REQUIRED
	description	CDATA 	#REQUIRED
>

<!ATTLIST property
	key CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ATTLIST value
	id		ID		#REQUIRED
	sdpId 	CDATA	#REQUIRED
	siteId 	CDATA 	#REQUIRED
>

=== chamuch/vtlcagw/cagw-core/src/main/resources/META-INF/cagw-core/be-config/config.xml
<!DOCTYPE config SYSTEM "config.dtd">
<config>
	<section id="DB_PROP" description="cagw backend url">
		<property key="cassandraAddress" value="192.168.5.136,192.168.5.142" />
		<property key="keySpaceName" value="cagw_keyspace" />
		<property key="poolSize" value="150" />
		<property key="keepAlive" value="30000" />
		<property key="queueSize" value="225" />
	</section>

	<!-- SCAPv2 : Considering 2 peers for commercial test -->
	<section id="Scap_Props_Occ" description="Scap_Props_Occ">
		<property key="ownProductId" value="Online Charging Control" />
		<property key="originRealm" value="ericsson.com" />
		<property key="ownFqdn" value="emmsgw01.viettel.com.vn" />
		<property key="ownTcpPort" value="3868" />
		<property key="ownTcpAddress" value="10.49.8.7" />
		<property key="peerCount" value="2" />
		<property key="threadPoolSize" value="100" />
		<property key="eventQueueSize" value="1200" />
		<property key="sendQueueSize" value="1200" />
		<property key="sendMessageLimit" value="150" />
		<property key="supportedVendor" value="193" />
		<property key="peer.1.address" value="aaa://10.49.5.134:3868;transport=tcp" />
		<property key="peer.1.hostId" value="eocc02.viettel.com.vn" />
		<property key="peer.1.realm" value="viettel.com.vn"/>
		<property key="peer.1.siteId" value="1" />
		<property key="peer.2.address" value="aaa://10.49.5.135:3868;transport=tcp" />
		<property key="peer.2.hostId" value="eocc03.viettel.com.vn" />
		<property key="peer.2.realm" value="viettel.com.vn" />
		<property key="peer.2.siteId" value="1" />
	</section>
	<section id="cs-air1" description="">
		<property key="ucipEndpointCount" value="2" />
		<property key="ownHostName" value="emmsgw01" />
		<property key="ownNodeType" value="1" />
		<property key="negotiatedCapabilities" value="805646916" />
		<property key="ucip.1.connectionTimeout" value="30000" />
		<property key="ucip.1.replyTimeout" value="30000" />
		<property key="ucip.1.idleTimeout" value="360000" />
		<property key="ucip.1.idleConnectionTimeoutInterval" value="60000" />
		<property key="ucip.1.maxConnections" value="40" />
		<property key="ucip.1.maxTotalConnections" value="60" />
		<property key="ucip.1.password" value="user" />
		<property key="ucip.1.retryCount" value="1" />
		<property key="ucip.1.staleCheckingEnabled" value="true" />
		<property key="ucip.1.useApacheHttpClient" value="true" />
		<property key="ucip.1.userAgent" value="UGw Server /5.0/1.0" />
		<property key="ucip.1.username" value="user" />
		<property key="ucip.1.soTimeout" value="120000" />
		<property key="ucip.1.urlAddress" value="http://10.57.249.76:10011/Air" />
		<property key="ucip.1.site" value="1" />
		<property key="ucip.1.defaultNai" value="1" />		
		<property key="ucip.2.connectionTimeout" value="30000" />
		<property key="ucip.2.replyTimeout" value="30000" />
		<property key="ucip.2.idleTimeout" value="360000" />
		<property key="ucip.2.idleConnectionTimeoutInterval" value="60000" />
		<property key="ucip.2.maxConnections" value="40" />
		<property key="ucip.2.maxTotalConnections" value="60" />
		<property key="ucip.2.password" value="user" />
		<property key="ucip.2.retryCount" value="1" />
		<property key="ucip.2.staleCheckingEnabled" value="true" />
		<property key="ucip.2.useApacheHttpClient" value="true" />
		<property key="ucip.2.userAgent" value="UGw Server /5.0/1.0" />
		<property key="ucip.2.username" value="user" />
		<property key="ucip.2.soTimeout" value="120000" />
		<property key="ucip.2.urlAddress" value="http://10.57.249.77:10011/Air" />
		<property key="ucip.2.site" value="1" />
		<property key="ucip.2.defaultNai" value="1" />	
	</section>	
	<section id="Water_Gate" description="">
		<property key="frontend" value="cagw-be1" />
		<property key="nodeThreshold" value="250" />
		<property key="systemWideThreshold" value="834" />
	</section>
</config>

=== chamuch/vtlcagw/cagw-core/src/main/resources/META-INF/cagw-core/mms-fe-config/config.xml
<!DOCTYPE config SYSTEM "config.dtd">
<config>

	<section id="Cagw_EndPoint" description="cagw backend url">
		<property key="Mmsc_Cagw_BackendUrl"
			value="http4://192.168.5.164:9090/cagw-backend/CgWeb/process" />
		<property key="Smpp_Cagw_BackendUrl"
		value="http4://192.168.5.164:9090/cagw-backend/CgWeb/process" />
	</section>

	<section id="DB_PROP" description="cagw backend url">
		<property key="cassandraAddress" value="192.168.5.136,192.168.5.142" />
		<property key="keySpaceName" value="cagw_keyspace" />
	</section>
    	
	<section id="GLOBAL_Alarms" description="Alarms">
		<property key="managementHost" value="10.57.249.136" />
		<property key="managementPort" value="162" />
		<property key="communityString" value="Ericsson/RASO/CAC" />
		<property key="timestampFormat" value="yyyy-MM-dd HH:mm:ss" />
		<property key="nodeName" value="mms-fe1" />
		<property key="applicationTrapOid" value="1.3.6.1.4.1.193.255.2.1.0.1" />
	</section>

	<!-- DCC : Considering 2 MMSC servers -->
	<section id="Dcc_Props1" description="Dcc_Props1">
		<property key="originRealm" value="viettel.com.vn" />
		<property key="acceptUnknownPeers" value="true" />
		<property key="accountId" value="10" />
		<property key="authId" value="4" />
		<property key="ownProductId" value="emmsgw01" />
		<property key="ownFqdn" value="emmsgw01.viettel.com.vn" />
		<property key="ownTcpPort" value="3868" />
		<property key="ownTcpAddress" value="emmsgw01.viettel.com.vn" />
		<property key="threadPoolSize" value="40" />
		<property key="eventQueueSize" value="3000" />
		<property key="sendQueueSize" value="3000" />
		<property key="sendMessageLimit" value="1200" />
		<property key="vendorId" value="0" />
		<property key="messageTimeout" value="30000" />
	</section>
	
	<section id="Water_Gate" description="">
		<property key="frontend" value="mms-fe1" />
		<property key="nodeThreshold" value="250" />
		<property key="systemWideThreshold" value="834" />
	</section>
</config>
